"""Execution traces attached by providers rather than generated by models."""

from pydantic import BaseModel, Field


class ExecutionProcess(BaseModel):
    """Preserve a provider's event sequence and reported token usage.

    Attributes:
        events: Original event or message objects in order, including tool calls,
            intermediate messages, and lifecycle events. Fields remain unchanged.
        usage: Provider-reported invocation usage mapping. Cached tokens are
            preserved as reported, not added to input tokens.
    """

    events: list[dict[str, object]] = Field(default_factory=list)
    usage: dict[str, object] = Field(default_factory=dict)
